service: serverless-bolt-po-scrapper-functions

#useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: eu-north-1
  role: arn:aws:iam::442771374669:role/General_Lambda_fullAccess  

plugins:
  - serverless-python-requirements  # we use node to install the dependency called serverless-python...
  #- serverless-dotenv-plugin # requested in order to use env variables

package: 
  individually: true  # include only specified files in the lambda package

functions:

  ConvertDict:
    name: Bolt-PO-SuppConverter
    handler: bolt_suppdict.handler
    module: handle_orders
    description: Bolt-PO lambda function that converts suppliers dictionary
    timeout: 180 # in seconds, max allowed time to run
    memorySize: 256 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

  MailBagger:
    name: Bolt-PO-MailBag
    handler: mail_bag.handler
    module: handle_orders
    description: Bolt-PO lambda function that generates the MailBag, first iteration
    timeout: 180 # in seconds, max allowed time to run
    memorySize: 512 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

  SuppMod_1:
    name: Bolt-PO-SuppMod-One
    handler: mod_1.handler
    module: handle_orders
    description: Bolt-PO lambda function that updates suppliers orders - v1
    timeout: 180 # in seconds, max allowed time to run
    memorySize: 512 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

  SuppMod_2:
    name: Bolt-PO-SuppMod-Two
    handler: mod_2.handler
    module: handle_orders
    description: Bolt-PO lambda function that updates suppliers orders - v2
    timeout: 180 # in seconds, max allowed time to run
    memorySize: 512 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

  Cleaner:
    name: Bolt-PO-s3Cleaner
    handler: clean.handler
    module: handle_orders
    description: deletes the working folder and save runtime files to s3
    timeout: 180 # in seconds, max allowed time to run
    memorySize: 512 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"